// <auto-generated />
using System;
using ArriendosApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArriendosApi.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArriendosApi.Entities.CobroMensual", b =>
                {
                    b.Property<int>("IdCobro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCobro"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<int?>("ContratoIdContrato")
                        .HasColumnType("integer");

                    b.Property<bool>("EsPagado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaUltimoPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdContrato")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SaldoAnterior")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalPagar")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorAgua")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorArriendo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorLuz")
                        .HasColumnType("numeric");

                    b.HasKey("IdCobro");

                    b.HasIndex("ContratoIdContrato");

                    b.ToTable("CobroMensual", (string)null);
                });

            modelBuilder.Entity("ArriendosApi.Entities.Contrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdContrato"));

                    b.Property<int>("DiaPagoMensual")
                        .HasColumnType("integer");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdInmueble")
                        .HasColumnType("integer");

                    b.Property<int>("IdInquilino")
                        .HasColumnType("integer");

                    b.Property<int?>("InmuebleIdInmueble")
                        .HasColumnType("integer");

                    b.Property<int?>("InquilinoIdInquilino")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoArriendo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoGarantia")
                        .HasColumnType("numeric");

                    b.HasKey("IdContrato");

                    b.HasIndex("InmuebleIdInmueble");

                    b.HasIndex("InquilinoIdInquilino");

                    b.ToTable("Contrato", (string)null);
                });

            modelBuilder.Entity("ArriendosApi.Entities.Edificio", b =>
                {
                    b.Property<int>("IdEdificio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEdificio"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEdificio");

                    b.ToTable("Edificio", (string)null);
                });

            modelBuilder.Entity("ArriendosApi.Entities.Inmueble", b =>
                {
                    b.Property<int>("IdInmueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInmueble"));

                    b.Property<int?>("EdificioIdEdificio")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<int>("IdEdificio")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroDepa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroMedidorAgua")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroMedidorLuz")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdInmueble");

                    b.HasIndex("EdificioIdEdificio");

                    b.ToTable("Inmueble", (string)null);
                });

            modelBuilder.Entity("ArriendosApi.Entities.Inquilino", b =>
                {
                    b.Property<int>("IdInquilino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInquilino"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("IdInquilino");

                    b.ToTable("Inquilino", (string)null);
                });

            modelBuilder.Entity("ArriendosApi.Entities.CobroMensual", b =>
                {
                    b.HasOne("ArriendosApi.Entities.Contrato", "Contrato")
                        .WithMany("CobrosMensuales")
                        .HasForeignKey("ContratoIdContrato");

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("ArriendosApi.Entities.Contrato", b =>
                {
                    b.HasOne("ArriendosApi.Entities.Inmueble", "Inmueble")
                        .WithMany("Contratos")
                        .HasForeignKey("InmuebleIdInmueble");

                    b.HasOne("ArriendosApi.Entities.Inquilino", "Inquilino")
                        .WithMany("Contratos")
                        .HasForeignKey("InquilinoIdInquilino");

                    b.Navigation("Inmueble");

                    b.Navigation("Inquilino");
                });

            modelBuilder.Entity("ArriendosApi.Entities.Inmueble", b =>
                {
                    b.HasOne("ArriendosApi.Entities.Edificio", "Edificio")
                        .WithMany("Inmuebles")
                        .HasForeignKey("EdificioIdEdificio");

                    b.Navigation("Edificio");
                });

            modelBuilder.Entity("ArriendosApi.Entities.Contrato", b =>
                {
                    b.Navigation("CobrosMensuales");
                });

            modelBuilder.Entity("ArriendosApi.Entities.Edificio", b =>
                {
                    b.Navigation("Inmuebles");
                });

            modelBuilder.Entity("ArriendosApi.Entities.Inmueble", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("ArriendosApi.Entities.Inquilino", b =>
                {
                    b.Navigation("Contratos");
                });
#pragma warning restore 612, 618
        }
    }
}
